Concert/Models/ErrorViewModel.cs
namespace Concert.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Concert/Controllers/HomeController.cs
using Concert.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Concert.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Concert/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Concert.DAL;
using Concert.DAL.Entities;

namespace Concert.Controllers
{
    public class TicketsController : Controller
    {
        private readonly DataBaseContext _context;

        public TicketsController(DataBaseContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
              return _context.Tickets != null ? 
                          View(await _context.Tickets.ToListAsync()) :
                          Problem("Entity set 'DataBaseContext.Tickets'  is null.");
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }
        public IActionResult ValidateTicket(string boletaId)
        {
            Guid id;

            if (!Guid.TryParse(boletaId, out id))
            {
                TempData["TicketInvalido"] ="Boleta No Válida";
            }
            else
            {
                var boleta = _context.Tickets.FirstOrDefault(t => t.Id == id);

                if (boleta == null)
                {
                    TempData["TicketInvalido"] ="Boleta No Valida";
                }
                else if (!boleta.IsUsed.ToString().ToLower().Equals("false"))
                {
                    TempData["TicketEnUso"] ="EL TICKET YA ESTA EN USO, AQUI TODA LA INFORMACION:";
                    return RedirectToAction("Details", new { id = boleta.Id });
                }
                else
                {
                    TempData["TicketValido"] ="INGRESE LA INFORMACION DEL TICKET:";
                    return RedirectToAction("Edit", new { id = boleta.Id });
                }
            }

            return RedirectToAction("Index");
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UseDate,IsUsed,EntranceGate")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticket.Id = Guid.NewGuid();
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,UseDate,IsUsed,EntranceGate")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Tickets == null)
            {
                return Problem("Entity set 'DataBaseContext.Tickets'  is null.");
            }
            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket != null)
            {
                _context.Tickets.Remove(ticket);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(Guid id)
        {
          return (_context.Tickets?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Concert/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">¡¡BIENVENIDO!!</h1>
    <h1 class="display-4">CONCIERTO LA BICHOTA</h1>

    <p>PARCIAL 3 DESAROLLO DE SOFTWARE POR SANTIAGO NOHABA</p>
</div>

Concert/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Concert </title> 
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Concert.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Concert</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">INICIO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">TIQUETES</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Concert - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Concert/Views/Tickets/Create.cshtml
@model Concert.DAL.Entities.Ticket

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UseDate" class="control-label"></label>
                <input asp-for="UseDate" class="form-control" />
                <span asp-validation-for="UseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsUsed" class="control-label"></label>
                <input asp-for="IsUsed" class="form-control" />
                <span asp-validation-for="IsUsed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntranceGate" class="control-label"></label>
                <input asp-for="EntranceGate" class="form-control" />
                <span asp-validation-for="EntranceGate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Concert/Views/Tickets/Delete.cshtml
@model Concert.DAL.Entities.Ticket

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsUsed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsUsed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntranceGate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntranceGate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Concert/Views/Tickets/Details.cshtml
@model Concert.DAL.Entities.Ticket

@{
    ViewData["Title"] = "Detalles";
}

<h1>¡¡ALERTA!!</h1>

<div>
    <h4>TICKET YA ESTA EN USO</h4>
    <br />
    @if (TempData["TicketEnUso"] != null)
    {
        <div class="alert alert-sucess">@TempData["TicketEnUso"]</div>
    }
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsUsed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsUsed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntranceGate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntranceGate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-outline-success">Regresar</a>
</div>

Concert/Views/Tickets/Edit.cshtml
@model Concert.DAL.Entities.Ticket

@{
    ViewData["Title"] = "Edit";
}

<h1>¡¡EXITO!!</h1>

<h4>TICKET VERIFICADO Y VALIDADO</h4>
<br /> 
@if (TempData["TicketValido"] != null)
{
    <div class="alert alert-sucess">@TempData["TicketValido"]</div>
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UseDate" class="control-label"></label>
                <input asp-for="UseDate" class="form-control" />
                <span asp-validation-for="UseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsUsed" class="control-label"></label>
                <input asp-for="IsUsed" class="form-control" />
                <span asp-validation-for="IsUsed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntranceGate" class="control-label"></label>
                <input asp-for="EntranceGate" class="form-control" />
                <span asp-validation-for="EntranceGate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-outline-success"  />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Concert/Views/Tickets/Index.cshtml
@model IEnumerable<Concert.DAL.Entities.Ticket>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">VALIDAR TICKET</h3>
            </div>
            <div class="panel-body">
                <form asp-action="ValidateTicket" method="post">
                    <div class="form-group">
                        <label>Id Ticket:</label>
                        <input type="text" name="boletaId" class="form-control" />
                    </div>
                    <br />
                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-success">VALIDAR</button>
                    </div>
                </form>
                <br />
                @if (TempData["TicketValido"] != null)
                {
                    <div class="alert alert-success">@TempData["TicketValido"]</div>
                }
                @if (TempData["TicketInvalido"] != null)
                {
                    <div class="alert alert-danger">@TempData["TicketInvalido"]</div>
                }
            </div>
        </div>
    </div>
</div>
<hr />

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Tickets</h3>
            </div>
            <div class="panel-body">
                <table class="table table-responsive table-striped" id="TicketTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.UseDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IsUsed)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EntranceGate)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UseDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsUsed)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EntranceGate)
                                </td>
                                <td>
                                    <!-- <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-success">Edit</a> -->
                                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info">Detalles</a>
                                    <!-- <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a> -->
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#TicketTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [5, 25, 50, 100, 200, -1],
                    [5, 25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>
}